apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calculator-storage-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: calculator-storage-pv
  storageClassName: nvme.network-drives.csi.timeweb.cloud
